### ISSUE TITLE
Editable example doesn't work with Conan 1.48

### ISSUE THREAD

**Issue by Sofahamster** [conan-io/examples#106]
The example in features/editable/cmake doesn't work at all. The provided build.sh script fails early because the `cmake-build-release` directory isn't created by the previous step `conan install .`. There are other issues as well. Also the files 'say.cpp' and 'say2.cpp' are byte-identical, shouldn't those two files be different to show how the editable mode works? 
Does anyone check these examples before or after releases to make sure they still work? Shouldn't this be automated in a CI pipeline somewhere?

**Comment by memsharded** [comment]
Yes, it seems one of the latest changes renamed ``conan`` => ``generators`` folder. Also apparently the original ``say.cpp`` was overwritten and comitted to git. Yes, it is true that these examples do not run with the releases. We are already focused on the ``examples2`` repo for Conan 2.0, not putting much effort in this one. We will run ``examples2`` nightly for 2.0.

Did https://github.com/conan-io/examples/pull/107 to fix it. Thanks very much for reporting!

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/examples/pull/108, thanks again!
