### ISSUE TITLE
VS2013: too many LNK2019 errors when compile the md5 sample.

### ISSUE THREAD

**Issue by netsesame2** [conan-io/examples#16]
Really don't know why, follow the steps in 
https://docs.conan.io/en/latest/getting_started.html

````
md5.obj : error LNK2019:  "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >
 __cdecl Poco::DigestEngine::digestToHex(class std::vector<unsigned char,class std::allocator<unsigned char> > const &)" (?digestToHex@Dig
estEngine@Poco@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV?$vector@EV?$allocator@E@std@@@4@@Z)
……
````

**Comment by netsesame2** [comment]
Got it! 
Poco is installed as x86_64 arch default, while md5 sample is compile in x86_32.

**Comment by jgsogo** [comment]
Hi! Nice you were able to find a solution for it. Sure you need the same `arch` setting for both, the library and the application.  👍 

Can we close the issue?

**Comment by jgsogo** [comment]
I'm closing it, but if you need anything else, let us know. Thanks
