### ISSUE TITLE
Directory structure for examples

### ISSUE THREAD

**Issue by uilianries** [conan-io/examples#2]
Hi!

We have been discussed how to improve our examples tree, since we can have name collision, like `protobuf` is too simple to be used.

@jgsogo said:

> About the new example in the examples repo: does it make sense to move it into `~/blog-DATE/protobuf`? I feel like there will be more examples related to `protobuf` (for cross-compiling), and we would like to keep this one matching what is written in the blogpost
(I suggest `blog-DATE`, but there could be a better naming for it)
...
We can edit the docs and this examples repo at the same time (ok, old docs will get outdated), but it is not usual to modify a blogpost
maybe we need scope for everything, `blog/XXXX/protobuf`, `docs/workspaces/....`, but for the blog I’m almost sure we need it

@uilianries said:

> why not just the title of blog post? We won't post twice at same date, and also for humans, it's easier to recognize by a name instead of looking for the date of  the blog post.
I really like the idea to separate `blog/` and `docs/`, but I think it could be:
`blog/serializing-your-data-with-protobuf/`, `docs/worspaces/`

@lasote said:

> not sure about separating by "docs" and "blog". That is just the origin not a categorization
> "features" and "libs" could make more sense.
> we can refactor later, the issue is not editing a blog post, is to remember

/cc @conan-io/barbarians

**Comment by memsharded** [comment]
Please rename the current to something shorter: ``protobuf`` for all examples related to protobuf. Then ``protobuf/sensor`` or ``protobuf/simple_serialization`` or something like that, simple and relative short.

Thanks

**Comment by uilianries** [comment]
Done!

**Comment by uilianries** [comment]
Ops! It's merged already. NP I gonna open a new PR to include folly

**Comment by uilianries** [comment]
Okay, we will follow @lasote idea: `features` and `libraries`.
