### ISSUE TITLE
linker error with examples/libraries/poco/md5

### ISSUE THREAD

**Issue by nickma82** [conan-io/examples#34]
# Occuring error
while trying to build the first example of https://docs.conan.io/en/latest/getting_started.html#installing-dependencies

```
[...]
+ cmake --build .
Scanning dependencies of target md5
[ 50%] Building CXX object CMakeFiles/md5.dir/md5.cpp.o
[100%] Linking CXX executable bin/md5
CMakeFiles/md5.dir/md5.cpp.o: In function `main':
md5.cpp:(.text.startup+0x9b): undefined reference to `Poco::DigestEngine::digestToHex[abi:cxx11](std::vector<unsigned char, std::allocator<unsigned char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/md5.dir/build.make:94: recipe for target 'bin/md5' failed
make[2]: *** [bin/md5] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/md5.dir/all' failed
make[1]: *** [CMakeFiles/md5.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

# Reproduction
(docker if you prefer `docker run --rm ubuntu:xenial bash -c 'bash'`)
```
# dependencies
apt update; apt install -qq -y --no-install-recommends build-essential cmake python3-pip git python3-setuptools
pip3 install conan

# checkout and build
git clone https://github.com/conan-io/examples.git && cd examples/libraries/poco/md5
./build.sh
```

Note: I turned on CMAKE_VERBOSE_MAKEFILE
```
diff --git a/libraries/poco/md5/CMakeLists.txt b/libraries/poco/md5/CMakeLists.txt
index ae4521f..f084d2b 100644
--- a/libraries/poco/md5/CMakeLists.txt
+++ b/libraries/poco/md5/CMakeLists.txt
@@ -1,5 +1,6 @@
 cmake_minimum_required(VERSION 2.8.12)
 project(MD5Encrypter)
+set(CMAKE_VERBOSE_MAKEFILE ON)
 
 if(CMAKE_VERSION VERSION_LESS 3.0.0)
     include(CheckCXXCompilerFlag)
```

**Comment by uilianries** [comment]
Hi @nickma82 !

Your error is related to ABI compatibility, please take a look here:
https://docs.conan.io/en/latest/howtos/manage_gcc_abi.html

To summarize, you need to update your profile to use libstdc++11:

    conan profile update compiler.libcxx=libstdc++11 default

Regards!

**Comment by nickma82** [comment]
Hi @uilianries and thanks for the quick answer! 
`conan profile update settings.compiler.libcxx=libstdc++11 default` (please note the added "settings.").

Further I'd like to point out that
a) Ubuntu Xenial packages are from the year 2016 and the likelihood that a lot of users are using that or later versions is presumably high 
b) This issue occurs with the *first* example in the *getting started* section [1]
.... And Issues with the first example are frustrating for a newcomer.

Best, Nick

[1] https://docs.conan.io/en/latest/getting_started.html

**Comment by danimtb** [comment]
@nickma82 glad you got it working. We will try to improve the *Important* message there for future users. Thanks!
