### ISSUE TITLE
Move editable example

### ISSUE THREAD

**Issue by uilianries** [conan-io/examples#41]
- Move https://github.com/memsharded/editables-examples to conan-io/examples repo.
- Update the blog post https://blog.conan.io/2019/02/04/New-conan-release-1-12.html

**Comment by uilianries** [comment]
Hmm, it's outdated actually. It uses the old command `conan link`

**Comment by memsharded** [comment]
Uhm, this example in my repo is not linked in the docs anymore, right? I think we should strongly prioritize updating the ones in the docs, the blog not that critical.

**Comment by uilianries** [comment]
Yes, it was using Conan link instead. I'll open another issue, let's update, but doing better, with a new example.

As an doing the slides for my talk, I needed to create a small example using editable packages. I gonna add it conan-io/example on this week

Also, I would say we need to update the blog. We don't need to post a new entire page, but add a warning as deprecated command there.
