### ISSUE TITLE
Update the imgui example to use reference from conan-center-index

### ISSUE THREAD

**Issue by danimtb** [conan-io/examples#43]
The imgui example is failing due to a missing dependency from bincrafters

```
ERROR: Failed requirement 'mesa-glu/9.0.1@bincrafters/stable' from 'glew/2.1.0@bincrafters/stable'
ERROR: Unable to find 'mesa-glu/9.0.1@bincrafters/stable' in remotes
```
https://travis-ci.org/conan-io/examples/jobs/646332791

We should update this example to use the packages from conan-center-index and avoid dependencies from the bincrafters remote, as it brakes users with only the conan-center remote configured (most of the cases)

**Comment by uilianries** [comment]
please, assign it to me
